# server configuration
server:
  port: 9900
  error:
    whitelabel:
      enabled: false
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shanoir_ng_import?useLegacyDatetimeCode=false&serverTimezone=Europe/Paris&characterEncoding=utf-8&useSSL=false
    username: shanoir
    password: shanoir
    # The SQL dialect makes Hibernate generate better SQL for the chosen database
    driver-class-name: com.mysql.jdbc.Driver
    initialize: false
  jackson:
    mapper:
      use-getters-as-setters: false
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      # Hibernate ddl auto (create, create-drop, update, validate)
      ddl-auto: validate
      # Naming strategy
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        connection:
          charset: UTF-8
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
  jooq:
    sql-dialect: Mysql
  http:
    multipart:
      maxFileSize: 500Mb
      maxRequestSize: 500Mb
  rabbitmq:
    host: shanoir-ng-rabbitmq
  session:
    store-type: none
front.server.url: http://shanoir-ng-nginx
#keycloak
keycloak:
  cors: true
  realm: shanoir-ng
  auth-server-url: http://localhost/auth
  ssl-required: external
  resource: shanoir-ng-import
  securityConstraints:
    - authRoles: 
      - ROLE_ADMIN
      - ROLE_EXPERT
      - ROLE_GUEST
      - ROLE_USER
    - securityCollections:
      - name: import secured api
      - patterns:
        - /*
# microservices url
ms.url:
  shanoir-ng-datasets: http://shanoir-ng-datasets/datasetacquisition
# logging configuration
logging:
  file: /vol/log/ms/shanoir-ng-import.log
  level:
    org.springframework.web: ERROR
    org.hibernate: ERROR
# Shanoir configurations
shanoir:
  import:
    upload:
      folder: /tmp
    # In a dicom file. Format "tag==value;" If it is not needed to separate image files into separated folders for a dicom serie.
    series:
      # this long name has been kept, as Elise and Isabelle know it like this; to find it for further adaptions in later time
      donotseparatedatasetsinserie: seriesDescription==*ASL*;seriesDescription==*asl*;protocolName==*ASL*;seriesDescription==*VIBE*DYN*;seriesDescription==*MoCoSeries*;seriesDescription==*DIFF*;seriesDescription==*Diff*;seriesDescription==*diff*;seriesDescription==*DTI*;seriesDescription==*DWI*;seriesDescription==*PERF*;seriesDescription==*Perf*;seriesDescription==*perf*;seriesDescription==*BOLD*;seriesDescription==*Bold*;seriesDescription==*bold*;seriesDescription==*intermediate t-Map*;protocolName==*DYN*;protocolName==*Dyn*;protocolName==*dyn*;seriesDescription==*QSM*;seriesDescription==*qsm*;seriesDescription==*RELAXO*;seriesDescription==*Relaxo*;
      # If in the serie, the dicom value equals the "value" for the "tag", then the serie will be considered as spectroscopy
      isspectroscopy: seriesDescription==*CSI*
  conversion:
    dcm2nii:
      converters:
        path:
          linux: /usr/local/dcm2niix-efd36a02e2a8e21acfbc62f41beeacf6731d67ac/build/bin/
          windows: 
        default: dcm2niix
        # Format "tag==value;". If in the serie, the dicom value equals the "value" for the "tag", then use clidcm instead of dcmnii to convert from dicom to nifti
        convertwithclidcm: seriesDescription==*Diff*;seriesDescription==*DIFF*;seriesDescription==*diff*;seriesDescription==*DTI*;seriesDescription==*DWI*;seriesDescription==*PERF*;seriesDescription==*Perf*;seriesDescription==*perf*; 
        # Format "tag==value;". If in the serie, the dicom value equals the "value" for the "tag", then output niftii file will be reconstructed as 4D volumes
        convertas4d: seriesDescription==*ASL*;seriesDescription==*asl*;protocolName==*ASL*;seriesDescription==*VIBE*DYN*;seriesDescription==*MoCoSeries*;seriesDescription==*DIFF*;seriesDescription==*Diff*;seriesDescription==*diff*;seriesDescription==*DTI*;seriesDescription==*DWI*;seriesDescription==*PERF*;seriesDescription==*Perf*;seriesDescription==*perf*;seriesDescription==*BOLD*;seriesDescription==*Bold*;seriesDescription==*bold*;seriesDescription==*intermediate t-Map*;protocolName==*DYN*;protocolName==*Dyn*;protocolName==*dyn*; 
        clidcm:
          path:
            linux: /opt/clidcm/libx64/clidcm
            windows: C:/Dev/workspace/Shanoir_Dev/external/clidcm/bin/windows/clidcm.exe
            lib: /opt/clidcm/libx64/

---

######################################
# DO NOT COMMIT VALUES MODIFICATIONS #
######################################
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://database:3306/import?useLegacyDatetimeCode=false&serverTimezone=Europe/Paris&characterEncoding=utf-8&useSSL=false
    username: import
    password: password
    # The SQL dialect makes Hibernate generate better SQL for the chosen database
    driver-class-name: com.mysql.jdbc.Driver
    data: classpath:/scripts/import.sql
    initialize: true
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      # Hibernate ddl auto (create, create-drop, update, validate)
      ddl-auto: create
      # Show or not log for each sql query
      show-sql: true
  jooq:
    sql-dialect: Mysql
  rabbitmq:
    host: localhost
server:
    port: 9903
front.server:
  address: http://shanoir-ng-nginx/shanoir-ng/
  url: http://shanoir-ng-nginx
#keycloak
keycloak:
  auth-server-url: http://shanoir-ng-nginx/auth
  credentials.secret: 4e6a17dd-04f1-4496-87f9-d8fbb219f88a
# microservices url
ms.url:
  shanoir-ng-datasets: http://datasets:9904/datasetacquisition
# logging configuration
logging:
  file: /var/log/shanoir-ng-logs/shanoir-ng-import.log
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR
    org.springframework.amqp: OFF
shanoir:
  import:
    upload:
      folder: /tmp

---

#################
# DO NOT CHANGE #
#################
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:SHANOIR_NG_IMPORT;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    data: classpath:/scripts/test-data-h2.sql
    initialize: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # Hibernate ddl auto (create, create-drop, update, validate)
      ddl-auto: create
logging:
  file: /tmp/shanoir-ng-import.log
---

#################
# DO NOT CHANGE #
#################
spring:
  profiles: qualif
  datasource:
    initialize: false
  jpa:
    hibernate:
      # Hibernate ddl auto (create, create-drop, update, validate)
      ddl-auto: validate
#keycloak
keycloak:
  auth-server-url: https://shanoir-qualif.irisa.fr/shanoir-ng/auth
