version: '3'
services:
  #
  # Keycloak: database and service
  #
  keycloak-database:
    container_name: keycloak-database
    image: mysql/mysql-server:5.7
    environment:
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=password
    volumes:
      - "keycloak-database-data:/var/lib/mysql"
    networks:
      - shanoir_ng_network
  keycloak:
    container_name: keycloak
    env_file:
      - ./docker-compose/keycloak/variables.env
    build: ./docker-compose/keycloak
    networks:
      - shanoir_ng_network
    ports:
      - "8080:8080"
    depends_on:
      - "keycloak-database"
  #
  # Database for all other microservices
  #
  database:
    container_name: database
    build: ./docker-compose/database
    volumes:
      - "database-data:/var/lib/mysql"
    ports:
     - "3307:3306"
    networks:
      - shanoir_ng_network
  #
  # Users microservice
  #
  users:
    container_name: users
    build: ./docker-compose/users
    volumes:
      - "logs:/var/log/shanoir-ng-logs"
    networks:
      - shanoir_ng_network
    ports:
     - "9901:9901"
     - "9911:9911"
    depends_on:
      - "keycloak"
      - "database"
  #
  # Studies microservice
  #
  studies:
    container_name: studies
    build: ./docker-compose/studies
    volumes:
      - "logs:/var/log/shanoir-ng-logs"
    networks:
      - shanoir_ng_network
    ports:
     - "9902:9902"
     - "9912:9912"
    depends_on:
      - "keycloak"
      - "database"
  #
  # Import microservice
  #
  import:
    container_name: import
    build: ./docker-compose/import
    volumes:
      - "logs:/var/log/shanoir-ng-logs"
      - "tmp:/tmp"
    networks:
      - shanoir_ng_network
    ports:
     - "9903:9903"
     - "9913:9913"
    depends_on:
      - "keycloak"
      - "database"
  #
  # Datasets microservice
  #
  datasets:
    container_name: datasets
    build: ./docker-compose/datasets
    volumes:
      - "logs:/var/log/shanoir-ng-logs"
      - "tmp:/tmp"
      - "datasets-data:/var/datasets-data"
    networks:
      - shanoir_ng_network
    ports:
     - "9904:9904"
     - "9914:9914"
    depends_on:
      - "keycloak"
      - "database"
  #
  # Backup PACS microservice: dcm4chee 5 arc-light
  #
  ldap:
    container_name: ldap
    image: dcm4che/slapd-dcm4chee:2.4.44-13.0
    logging:
      driver: json-file
      options:
        max-size: "10m"
    networks:
      - shanoir_ng_network
    ports:
      - "389:389"
    env_file: ./docker-compose/dcm4chee/variables.env
    volumes:
      - "dcm4chee-ldap-data:/var/lib/ldap"
      - "dcm4chee-sldap-data:/etc/ldap/slapd.d"
  dcm4chee-database:
    container_name: dcm4chee-database
    image: dcm4che/postgres-dcm4chee:10.0-13
    logging:
      driver: json-file
      options:
        max-size: "10m"
    networks:
      - shanoir_ng_network
    ports:
      - "5432:5432"
    env_file: ./docker-compose/dcm4chee/variables.env
    volumes:
      - "dcm4chee-database-data:/var/lib/postgresql/data"
  dcm4chee-arc:
    container_name: dcm4chee-arc
    image: dcm4che/dcm4chee-arc-psql:5.13.0
    logging:
      driver: json-file
      options:
        max-size: "10m"
    networks:
      - shanoir_ng_network
    ports:
      - "8081:8081"
      - "8443:8443"
      - "9990:9990"
      - "11112:11112"
      - "2575:2575"
    env_file: ./docker-compose/dcm4chee/variables.env
    environment:
      WILDFLY_CHOWN: /opt/wildfly/standalone /storage
      WILDFLY_WAIT_FOR: ldap:389 dcm4chee-database:5432
    depends_on:
      - "ldap"
      - "dcm4chee-database"
    volumes:
      - "dcm4chee-arc-wildfly-data:/opt/wildfly/standalone"
      - "dcm4chee-arc-storage-data:/storage"
  #
  # Nginx
  #
  nginx:
    container_name: shanoir-ng-nginx
    build: ./docker-compose/nginx
    volumes:
      - "logs:/var/log/nginx"
      - "/home/julien/projects/shanoir-ng/shanoir-ng-front/mnt-dist:/etc/nginx/html/"
    networks:
      - shanoir_ng_network
    ports:
     - "80:80"
    depends_on:
      - "keycloak"
      - "users"
      - "studies"
      - "import"
      - "datasets"
      - "dcm4chee-arc"

volumes:
  keycloak-database-data:
  database-data:
  datasets-data:
  dcm4chee-ldap-data:
  dcm4chee-sldap-data:
  dcm4chee-database-data:
  dcm4chee-arc-wildfly-data:
  dcm4chee-arc-storage-data:
  tmp:
  logs:

networks:
  shanoir_ng_network: