######################################
# Default profile is production      #
######################################
server:
  port: 9904
  error:
    whitelabel:
      enabled: false
##### Database #####
spring:
  datasource:
    url: jdbc:mysql://database:3306/datasets?useLegacyDatetimeCode=false&serverTimezone=Europe/Paris&characterEncoding=utf-8&useSSL=false
    username: datasets
    password: password
    # The SQL dialect makes Hibernate generate better SQL for the chosen database
    driver-class-name: com.mysql.jdbc.Driver
    initialize: false
    data: classpath:/scripts/import.sql
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      # Hibernate ddl auto (create, create-drop, update, validate)
      ddl-auto: validate
      # Naming strategy
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        connection:
          charset: UTF-8
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
##### Others #####
  jackson:
    mapper:
      use-getters-as-setters: false
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  jooq:
    sql-dialect: Mysql
#  rabbitmq:
#    host: rabbitmq
  session:
    store-type: none
front.server:
  address: http://shanoir-ng-nginx/shanoir-ng/
  url: http://shanoir-ng-nginx
##### Keycloak #####
keycloak:
  # attention: this config for the token issuer needs to match the domain of the frontend
  # used for token creation AND the server url needs to be known from inside the docker network:
  auth-server-url: http://shanoir-ng-nginx/auth
  cors: true
  realm: shanoir-ng
  resource: shanoir-ng-datasets
  ssl-required: external
  securityConstraints:
    - authRoles: 
      - ROLE_ADMIN
      - ROLE_EXPERT
      - ROLE_GUEST
      - ROLE_USER
    - securityCollections:
      - name: datasets secured api
      - patterns:
        - /*
# microservices url
ms.url:
  shanoir-ng-studies: http://studies:9902/
datasets-data: /var/datasets-data
# logging configuration
logging:
  file: /var/log/shanoir-ng-logs/shanoir-ng-datasets.log
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR
    org.springframework.amqp: OFF
        
  
### ============================================================= ###
##                  Dicom Server Configuration                    ##
### ============================================================= ###
dcm4chee-arc:
  address: http://dcm4chee-arc:8081
  wado-rs: /dcm4chee-arc/aets/DCM4CHEE/rs/studies

---

######################################
# DO NOT COMMIT VALUES MODIFICATIONS #
######################################
spring:
  profiles: dev
  datasource:
    initialize: true
  jpa:
    hibernate:
      # Hibernate ddl auto (create, create-drop, update, validate)
      ddl-auto: create
    # Show or not log for each sql query
    show-sql: true

# logging configuration
logging:
  file: /var/log/shanoir-ng-logs/shanoir-ng-datasets.log
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR