######################################
# Default profile is production      #
######################################
server:
  port: 9902
  error:
    whitelabel:
      enabled: false
##### Database #####
spring:
  datasource:
    url: jdbc:mysql://database:3306/studies?useLegacyDatetimeCode=false&serverTimezone=Europe/Paris&characterEncoding=utf-8&useSSL=false
    username: studies
    password: password
    # The SQL dialect makes Hibernate generate better SQL for the chosen database
    driver-class-name: com.mysql.jdbc.Driver
    initialize: false
    data: classpath:/scripts/import.sql
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      # Hibernate ddl auto (create, create-drop, update, validate)
      ddl-auto: validate
      # Naming strategy
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        connection:
          charset: UTF-8
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
##### Others #####
  jackson:
    mapper:
      use-getters-as-setters: false
  jooq:
    sql-dialect: Mysql
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  session:
    store-type: none
front.server:
  address: https://shanoir-ng-nginx/shanoir-ng/
  url: https://shanoir-ng-nginx
##### Keycloak #####
keycloak:
  # attention: this config for the token issuer needs to match the domain of the frontend
  # used for token creation AND the server url needs to be known from inside the docker network:
  auth-server-url: https://shanoir-ng-nginx/auth
  cors: true
  realm: shanoir-ng
  resource: shanoir-ng-studies
  ssl-required: external
  securityConstraints:
    - authRoles: 
      - ROLE_ADMIN
      - ROLE_EXPERT
      - ROLE_GUEST
      - ROLE_USER
    - securityCollections:
      - name: studies secured api
      - patterns:
        - /*
# microservices url
ms.url:
  shanoir-ng-users: http://users:9901/users
  shanoir-ng-import: http://import:9903/niftiConverter
  shanoir-ng-studycards: http://datasets:9904/studycards
  shanoir-ng-examinations: http://datasets:9904/examinations
# logging configuration
logging:
  file: /var/log/shanoir-ng-logs/shanoir-ng-studies.log
  level:
    org.shanoir: WARN
    org.springframework.web: ERROR
    org.hibernate: ERROR

---

######################################
# DO NOT COMMIT VALUES MODIFICATIONS #
######################################
spring:
  profiles: dev
  datasource:
    initialize: true
  jpa:
    hibernate:
      # Hibernate ddl auto (create, create-drop, update, validate)
      ddl-auto: create
    # Show or not log for each sql query
    show-sql: true

# logging configuration
logging:
  file: /var/log/shanoir-ng-logs/shanoir-ng-studies.log
  level:
    org.shanoir: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: ERROR
    org.springframework.amqp: OFF
    
    
---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:SHANOIR_NG_STUDY;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    initialize: true
    data: classpath:/scripts/test-data-h2.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # Hibernate ddl auto (create, create-drop, update, validate)
      ddl-auto: create-drop